// Generated by https://quicktype.io

export interface PaginatedClients {
    first: number;
    prev: null;
    next: number;
    last: number;
    pages: number;
    items: number;
    data: Client[];
}

export interface Client {
    id: string;
    name: string;
    isActive: boolean;
    picture: string;
    age: number;
    eyeColor: string;
    gender: Gender;
    company: string;
    email: string;
    phone: string;
    address: string;
}

export enum Gender {
    Female = "female",
    Male = "male",
}
